set nocompatible              " required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

" Add all your plugins here (note older versions of Vundle used Bundle instead of Plugin)
Plugin 'tmhedberg/SimpylFold'
Plugin 'vim-scripts/indentpython.vim'
Plugin 'scrooloose/syntastic'
Plugin 'nvie/vim-flake8'
Plugin 'jnurmine/Zenburn'
Plugin 'vim-airline/vim-airline'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

set backspace=indent,eol,start
set number
set mouse=r
set ruler
" Ignore case when searching
set ignorecase
set expandtab
set shiftwidth=4
set tabstop=4
set smarttab
set guioptions+=aA

set colorcolumn=80
syntax on
"Highlight search things
set hlsearch

"Show matching bracets when text indicator is over them
set showmatch

"Make search act like search in modern browsers
set incsearch

"Auto indent
set ai
"Smart indet
set si

"Wrap lines
set wrap

" Merge selection and system clipboard
set clipboard=unnamedplus

set guifont=ProggyCleanTT\ 16
set matchpairs=(:),{:},[:],<:>
set matchtime=2
set wildmode=longest:list,full
set ttyfast

" Enable folding
set foldmethod=indent
set foldlevel=99
" Enable folding with the spacebar
nnoremap <space> za
let g:SimpylFold_docstring_preview=1

"split navigations
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" Map W and Q to do the same thing as w and q
:command WQ wq
:command Wqa wqa
:command Wq wq
:command W w
:command Q q

let python_highlight_all=1

" arrow keys behave as expected
set whichwrap+=<,>,[,]


" enable 256 colors and zenburn scheme
set t_Co=256
colors zenburn

" set the search scan to wrap lines
set wrapscan

" When vimrc is edited, reload it
autocmd! bufwritepost vimrc source ~/.vimrc

" Show the current command in the lower right corner
set showcmd

" Lines above/below cursor when scrolling
set scrolloff=5

" Minimal columns displayed when scrolling horizontally
set sidescrolloff=5

" Highlight trailling white spaces
match Todo /\s\+$/

" Remove trailing white space
autocmd BufWritePre * :%s/\s\+$//e

" Show file name at the bottom
set modeline
set ls=2

" Highlight current line
set cursorline
hi CursorLine term=bold cterm=bold guibg=Grey40

" Set python coding style when opening .py file
autocmd BufNewFile,BufRead *.py setlocal tabstop=4 softtabstop=4 shiftwidth=4 textwidth=79 expandtab autoindent fileformat=unix

" Set line width to 72 for git commit message
autocmd Filetype gitcommit setlocal spell textwidth=72
