# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="powerlevel10k/powerlevel10k"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line to change how often to auto-update (in days).
# zstyle ':omz:update' frequency 13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
HIST_STAMPS="yyyy-mm-dd"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

source $ZSH/oh-my-zsh.sh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Aliases
alias ll='ls -alh --color'
alias vi='vim'
alias grep='grep --color'
alias vbash='vim ~/.zshrc'
alias srcbash='source ~/.zshrc'
alias vgit='vim ~/.gitconfig'
alias exit='say peace out; \exit'
alias please='sudo'
alias gimme='curl -LfO'

# Pagination in the same "console"
export PAGER=""

## EnergyHub

# Added by devenv/dev-machine-setup Fri Nov 18 15:34:37 EST 2022
export PATH="${PATH}:/Users/bvidal/work/devenv/bin"
[ -f "/Users/bvidal/work/devenv/lib/eh_functions.sh" ] && . /Users/bvidal/work/devenv/lib/eh_functions.sh

# EH vars
export EH_DEVENV_PREFIX="/Users/bvidal/work/devenv"
export SCRIPTS_HOME="/Users/bvidal/work/scripts"

# All the secret stuff!
[ -f "/Users/bvidal/.secrets" ] && . /Users/bvidal/.secrets

# Python
export PYTHONPATH="${PYTHONPATH}:/Users/bvidal/work/scripts"

# Dev stuff
export PATH="/opt/homebrew/opt/openjdk@11/bin:/opt/homebrew/opt/mysql-client/bin/:$PATH"

# pyenv
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

# jenv
export PATH="$HOME/.jenv/bin:$PATH"
eval "$(jenv init -)"

## Functions

# yay or nay command
function yon() {
    RESULT=$?
    COMMAND=`which say 2>/dev/null`
    [ $? -eq 1 ] && COMMAND=`which echo`
    [ $RESULT -eq 0 ] && $COMMAND "IT'S A BINGO" || $COMMAND "YOU FAILED"
    return $RESULT
}

# source python virtualenv, defaults to env or venv
function senv(){
  [ -d env  ] && ENV_DIR=env || ENV_DIR=venv
  [ $# -eq 1 ] && ENV_DIR=$1
  source $ENV_DIR/bin/activate
}

# create a dir and cd into it
function mkcd(){
  mkdir -p $1 && cd $1
}

# dot file functions
[ -f ~/.dotfile.sh ] && source ~/.dotfile.sh

