# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# don't put duplicate lines in the history. See bash(1) for more options
export HISTCONTROL=ignoredups
export HISTFILESIZE=
export HISTSIZE=
export HISTTIMEFORMAT="[%F %T] "
# Change the file location because certain bash sessions truncate .bash_history file upon close.
# http://superuser.com/questions/575479/bash-history-truncated-to-500-lines-on-each-login
export HISTFILE=~/.bash_eternal_history
# Force prompt to write history after every command.
# http://superuser.com/questions/20900/bash-history-loss
PROMPT_COMMAND="history -a; $PROMPT_COMMAND"

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# setup ls color properly
export LSCOLORS=ExFxBxDxCxegedabagacad

# make less more friendly for non-text input files, see lesspipe(1)
#[ -x /usr/bin/lesspipe ] && eval "$(lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "$debian_chroot" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

export TERM=xterm-256color

alias vi='vim'
alias ll='ls -AlhG'
if [ -z "$debian_chroot" ]; then
  alias ll='ls -alh --color'
fi
alias l='ll'
alias grep='grep --colour'
alias egrep='egrep --colour'
alias ntl='nautilus ./ 2>/dev/null &'
alias vbash='vi ~/.bashrc'
alias srcbash='. ~/.bashrc'
alias setbg="awsetbg -f $HOME/Pictures/bg.jpg"
alias vawesome="vi ~/.config/awesome/rc.lua"
alias openid='echo http://bvidal-ltutech-com.myopenid.com/'
alias vgit='vi ~/.gitconfig'
alias dmesg='dmesg -T'
alias generate_password='< /dev/urandom tr -dc A-Za-z0-9 | head -c${1:-8};echo;'

# crowdtwist specifics
export COMPOSE_HTTP_TIMEOUT=500
alias dc="docker-compose -f ~/crowdtwist/docker/docker-compose.yml"
alias jump='ssh bvidal@shell01.crowdtwist.com'
alias auth='cd ~/tools/ && java -classpath ./ Authenticator.Main /Users/bertrandvidal/.google_authenticator'
alias unmount-web-app="diskutil unmountDisk ~/crowdtwist/git/web"
alias mount-web-app="sshfs root@127.0.0.1:/opt/crowdtwist/ ~/crowdtwist/git/web -o reconnect -o workaround=all -o volname=ct-server -o Ciphers=arcfour -C -p $(docker inspect --format='{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}' web 2> /dev/null)"


if [ -f /Users/bertrandvidal/crowdtwist/docker/local.env.sh ];
  then
    launchctl setenv CT_ENVIRONMENT local
    export CT_ENVIRONMENT=local
fi

function dc_bash(){
  docker exec -ti $1 bash
}

function dc_log(){
  docker exec $1 tail -n 200 -f /root/output.log
}

function dc_restart(){
  docker exec $1 restart
}

function dc_rebuild(){
  docker exec $1 rebuild
}

function gtest() {
 # run gradle tess
 pushd ~/crowdtwist/git/J > /dev/null 2>&1
 for m in $*
   do
     ./gradlew modules:$m:clean modules:$m:test modules:$m:installApp -S --refresh-dependencies --rerun-tasks
   done
 popd > /dev/null 2>&1
}



# utility functions

function senv(){
  ENV_DIR=env
  [ $# -eq 1 ] && ENV_DIR=$1
  source $ENV_DIR/bin/activate
}

# create and source a virtualenv in the current directory
function create_env(){
  ENV_DIR=env-$RANDOM
  [ $# -eq 1 ] && ENV_DIR=$1
  virtualenv --distribute $ENV_DIR && source $ENV_DIR/bin/activate
}

# create a dir and cd into it
function mkcd(){
  mkdir -p $1 && cd $1
}

# grep the first parameter un ps aux
function psgp(){
 ps faux | grep -v grep | grep -i $1
}


# recursively grep the first argument
function rgp(){
 egrep -rniI "$1" *
}

# kill a process by name
function killbyname(){
 kill `ps aux | grep $1 | grep -v grep | awk '{print $2}'`
}

# search a word on google
function google(){
query=
for word in $*
do
  query="${query}+${word}"
done
 x-www-browser http://www.google.com/search?q=$query >/dev/null &
}

#kill process holding the specified file
function fdkill(){
  lsof $1 | grep -v PID | kill -9 `awk '{print $2}'`
}


# allows to grep the parameter in any python file
function pygrep(){
 SEARCH_PATH="."
 [ $# -gt 1 ] && SEARCH_PATH=$2
 find $SEARCH_PATH -name "*.py" -not -path "./env/*" -and -not -path "./*egg*/*" -exec egrep --color -in $1 {} +
}

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
fi
if [ `which brew`  ] && [ -f $(brew --prefix)/etc/bash_completion ]; then
  . $(brew --prefix)/etc/bash_completion
fi
if [ -f /usr/local/etc/bash_completion.d/docker-compose ]; then
    . /usr/local/etc/bash_completion.d/docker-compose
fi

# dot file functions
[ -f ~/.dotfile.sh ] && source ~/.dotfile.sh

# git/prompt file
GIT_PS1_SHOWDIRTYSTATE=1
GIT_PS1_SHOWUNTRACKEDFILES=1
GIT_PS1_SHOWUPSTREAM="auto verbose develop"
[ -f ~/.git.bash ] && source ~/.git.bash


# ssh agent
[ -f ~/.ssh/id_rsa ] && ssh-add -K ~/.ssh/id_rsa 1>/dev/null 2>&1

# add bash to wakatime - https://wakatime.com/help/plugins/terminal
[ -f ~/github/bash-wakatime/bash-wakatime.sh ]  && source ~/github/bash-wakatime/bash-wakatime.sh;

# pythonrc for completion and history
[ -f $HOME/.pythonrc.py ] && export PYTHONSTARTUP=~/.pythonrc.py

# Color mapping
grey='\[\033[1;30m\]'
red='\[\033[0;31m\]'
RED='\[\033[1;31m\]'
green='\[\033[0;32m\]'
GREEN='\[\033[1;32m\]'
yellow='\[\033[0;33m\]'
YELLOW='\[\033[1;33m\]'
purple='\[\033[0;35m\]'
PURPLE='\[\033[1;35m\]'
white='\[\033[0;37m\]'
WHITE='\[\033[1;37m\]'
blue='\[\033[0;34m\]'
BLUE='\[\033[1;34m\]'
cyan='\[\033[0;36m\]'
CYAN='\[\033[1;36m\]'
NC='\[\033[0m\]'

COLORS=($grey $red $RED $green $GREEN $yellow $yellow $purple $PURPLE $blue $BLUE $cyan $CYAN)

# (env)[clock]user@host:[git_status]cwd$
CHROOT='${debian_chroot:+($debian_chroot)}'
GIT_PROMPT='$(__git_ps1 "[%s]")'
# only numbers of the md5 of the hostname
[ `which md5sum` ] && MD5_BIN=md5sum || MD5_BIN=md5
HOST_MD5=`echo -n $HOSTNAME | $MD5_BIN | cut -d " " -f 1 | sed 's/[a-z]//g'`
# modulo the last 8 digits of the hostname's md5 by the length of the colors array
HOST_DIGIT=`expr ${HOST_MD5:8} % ${#COLORS[@]}`
HOST_COLOR="${COLORS[$HOST_DIGIT]}"

export PS1="$CHROOT$cyan[\A]$RED\u$NC@$HOST_COLOR\H$NC:$GREEN$GIT_PROMPT$NC\W\$ "

# CrowdTwist Stuff
if [ -f /opt/tns/tnsnames.ora ];
then
	alias npm="echo Don\'t use npm, use ied && echo > /dev/null"
	export IOTK_CONF=/opt/crowdtwist/conf/iotk/local/iotk_conf.php
	export IOTK_SERVER_ENVIRONMENT=local
	export TNS_ADMIN=/opt/tns
	export CT_SITE_DOMAIN=crowdtwist.com
	export CT_CLIENT_ID=2
	export CT_CLIENT_DOMAIN=rosigolan.crowdtwist.com
	export CT_SITE_ID=1
	export IED_CACHE_DIR=/opt/crowdtwist/.ied_cache
	export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/crowdtwist/app/bin:/root/bin:/usr/lib/oracle/12.1/client64/bin
	. iset crowdtwist > /dev/null 2>&1
	. testsite > /dev/null 2>&1
	export NLS_LANG=American_America.AL32UTF8
	# Oracle sqlplus setup
	ORACLE_HOME=/usr/lib/oracle/12.1/client64
	LD_LIBRARY_PATH=/usr/lib/oracle/12.1/client64/lib
	export ORACLE_HOME
	export LD_LIBRARY_PATH
	export PATH
	DISABLE_AUTO_UPDATE=true
    cd /opt/crowdtwist
fi

# Docker environmental variables
export SFTP_UID=501
export J_REPO_PATH=/Users/bertrandvidal/crowdtwist/git/J
export USER_FILES_PATH=/Users/bertrandvidal/crowdtwist/docker_files
export SFTP_DIRECTORY=/Users/bertrandvidal/crowdtwist/docker_sftp
